name = "Lithe"
license = "MIT"
licenselink = "https://github.com/roguh/lithe/master/LICENSE.md"
description = "Lightweight Hugo theme"
homepage = "https://github.com/roguh/lithe"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive"
]
features = [
  "accessibility",
  "analytics",
  "comments",
  "cover-image",
  "favicon",
  "multilingual",
  "opengraph",
  "pagination",
  "shortcodes",
  "single-column",
  "social-menu",
  "syntax-highlighting",
  "search"
]
min_version = 0.28

[author]
  name = "roguh"
  homepage = "https://roguh.com"

[original]
  name = "ribice"
  homepage = "https://ribice.ba"
  repo = "https://github.com/ribice/hemingway"

[original]
  name = "hemingway"
  homepage = "http://tanksuzuki.com"
  repo = "https://github.com/tanksuzuki/hemingway"
